modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
authors="${mod_authors}"
modId="rosetta_library"
version="${version}"
displayName="Rosetta"
logoFile="logo.png"
description='''${mod_description}'''

[[dependencies.rosetta_library]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
