modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

issueTrackerURL="${mod_issues}"

[[mods]]
authors="${mod_authors}"
modId="rosetta_library"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
logoFile="logo.png"
description='''${mod_description}'''

[[dependencies.rosetta_library]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
