modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
authors="${mod_authors}"
modId="rosetta_library"
version="${version}"
displayName="Rosetta"
${icon_property}="logo.png"
description='''${mod_description}'''

[[dependencies.rosetta_library]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
