modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

issueTrackerURL="${mod_issues}"

[[mods]]
modId="rosetta_attachments"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
${icon_property}="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.rosetta_attachments]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.rosetta_attachments]]
modId="rosetta_library"
type="required"
versionRange="[${rosetta_version},)"
ordering="AFTER"
side="BOTH"
