modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

issueTrackerURL="${mod_issues}"

[[mods]]
modId="rosetta_resources"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
authors="${mod_authors}"
description='''${mod_description}'''
${icon_property}="logo.png"

[[dependencies.rosetta_resources]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.rosetta_resources]]
modId="rosetta_library"
type="required"
versionRange="[${rosetta_version},)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="runeweaver.mixins.json"
