modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
authors="${mod_authors}"
modId="rosetta_config"
version="${version}"
displayName="Rosetta Config"
description='''${mod_description}'''

[[dependencies.rosetta_config]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.rosetta_config]]
modId="rosetta_library"
type="required"
versionRange="[${rosetta_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.rosetta_config]]
modId="midnightlib"
type="required"
versionRange="[${midnight_version},)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="rosetta-config.mixins.json"

[[dependencies.rosetta_config]]
modId="rosetta_networking"
type="required"
versionRange="[${rosetta_version},)"
ordering="AFTER"
side="BOTH"
