modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

issueTrackerURL="${mod_issues}"

[[mods]]
modId="rosetta_resources_sync"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.rosetta_resources_sync]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.rosetta_resources_sync]]
modId="rosetta_library"
mandatory=true
versionRange="[${rosetta_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.rosetta_resources_sync]]
modId="rosetta_networking"
mandatory=true
versionRange="[${module_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.rosetta_resources_sync]]
modId="rosetta_resources"
mandatory=true
versionRange="[${module_version},)"
ordering="AFTER"
side="BOTH"
