modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

issueTrackerURL="${mod_issues}"

[[mods]]
authors="${mod_authors}"
modId="rosetta_config"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
logoFile="logo.png"
description='''${mod_description}'''

[[dependencies.rosetta_config]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.rosetta_config]]
modId="rosetta_library"
mandatory=true
versionRange="[${rosetta_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.rosetta_config]]
modId="midnightlib"
mandatory=true
versionRange="[${midnight_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.rosetta_config]]
modId="rosetta_networking"
mandatory=true
versionRange="[${rosetta_version},)"
ordering="AFTER"
side="BOTH"
